export const bubbleProps = {
  formData: {
    xAxisLabel: 'SUM(na_sales)',
    yAxisLabel: 'SUM(eu_sales)',
    xAxisTickLabelAngle: 0,
    yAxisLabelAngle: 90,
    xAxisLogScale: false,
    yAxisLogScale: false,
    width: 994,
    height: 233.40663792811355,
    bubbleSize: 1000,
    legendPosition: 'top',
    showGridLines: true,
    numbersFormat: 'SMART_NUMBER',
    entity: 'publisher',
    series: 'genre',
    xAxis: 'SUM(na_sales)',
    yAxis: 'SUM(eu_sales)',
    zAxis: 'SUM(global_sales)',
  },
  height: 400,
  queriesData: [
    {
      data: [
        {
          publisher: 'Aksys Games',
          genre: 'Adventure',
          'SUM(na_sales)': 0.09,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.14,
        },
        {
          publisher: 'T&E Soft',
          genre: 'Sports',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.12,
        },
        {
          publisher: 'Xplosiv',
          genre: 'Misc',
          'SUM(na_sales)': 0.21,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.23,
        },
        {
          publisher: 'Disney Interactive Studios',
          genre: 'Action',
          'SUM(na_sales)': 29.9,
          'SUM(eu_sales)': 16.5,
          'SUM(global_sales)': 52.2,
        },
        {
          publisher: 'Hudson Soft',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0.08,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 1.87,
        },
        {
          publisher: 'Disney Interactive Studios',
          genre: 'Platform',
          'SUM(na_sales)': 6.37,
          'SUM(eu_sales)': 2.73,
          'SUM(global_sales)': 9.85,
        },
        {
          publisher: 'Big Fish Games',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Oxygen Interactive',
          genre: 'Adventure',
          'SUM(na_sales)': 0.15,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.18,
        },
        {
          publisher: 'ESP',
          genre: 'Simulation',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.06,
        },
        {
          publisher: 'Pack In Soft',
          genre: 'Simulation',
          'SUM(na_sales)': 0.25,
          'SUM(eu_sales)': 0.06,
          'SUM(global_sales)': 0.48,
        },
        {
          publisher: 'PopTop Software',
          genre: 'Strategy',
          'SUM(na_sales)': 0.06,
          'SUM(eu_sales)': 0.04,
          'SUM(global_sales)': 0.11,
        },
        {
          publisher: 'Accolade',
          genre: 'Racing',
          'SUM(na_sales)': 1.05,
          'SUM(eu_sales)': 0.2,
          'SUM(global_sales)': 1.3,
        },
        {
          publisher: 'THQ',
          genre: 'Simulation',
          'SUM(na_sales)': 5.4,
          'SUM(eu_sales)': 1.44,
          'SUM(global_sales)': 7.84,
        },
        {
          publisher: 'Warner Bros. Interactive Entertainment',
          genre: 'Adventure',
          'SUM(na_sales)': 0.31,
          'SUM(eu_sales)': 0.19,
          'SUM(global_sales)': 0.59,
        },
        {
          publisher: 'Avanquest',
          genre: 'Sports',
          'SUM(na_sales)': 0.05,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.08,
        },
        {
          publisher: 'Aqua Plus',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.11,
        },
        {
          publisher: 'D3Publisher',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0.5,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.69,
        },
        {
          publisher: 'Hudson Soft',
          genre: 'Shooter',
          'SUM(na_sales)': 0.32,
          'SUM(eu_sales)': 0.06,
          'SUM(global_sales)': 1.23,
        },
        {
          publisher: 'Phenomedia',
          genre: 'Racing',
          'SUM(na_sales)': 0.03,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'UFO Interactive',
          genre: 'Misc',
          'SUM(na_sales)': 0.61,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.64,
        },
        {
          publisher: 'Agatsuma Entertainment',
          genre: 'Platform',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'Psygnosis',
          genre: 'Adventure',
          'SUM(na_sales)': 0.2,
          'SUM(eu_sales)': 0.14,
          'SUM(global_sales)': 0.42,
        },
        {
          publisher: 'Pony Canyon',
          genre: 'Misc',
          'SUM(na_sales)': 0.03,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: 'ASCII Entertainment',
          genre: 'Adventure',
          'SUM(na_sales)': 0.07,
          'SUM(eu_sales)': 0.05,
          'SUM(global_sales)': 0.71,
        },
        {
          publisher: 'Datam Polystar',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'Take-Two Interactive',
          genre: 'Platform',
          'SUM(na_sales)': 2.46,
          'SUM(eu_sales)': 0.63,
          'SUM(global_sales)': 3.34,
        },
        {
          publisher: 'Just Flight',
          genre: 'Simulation',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'Little Orbit',
          genre: 'Adventure',
          'SUM(na_sales)': 0.23,
          'SUM(eu_sales)': 0.65,
          'SUM(global_sales)': 0.97,
        },
        {
          publisher: 'THQ',
          genre: 'Action',
          'SUM(na_sales)': 54.37,
          'SUM(eu_sales)': 24.83,
          'SUM(global_sales)': 89.2300000000001,
        },
        {
          publisher: 'Phantagram',
          genre: 'Simulation',
          'SUM(na_sales)': 0.03,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: 'O3 Entertainment',
          genre: 'Simulation',
          'SUM(na_sales)': 0.1,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.11,
        },
        {
          publisher: 'From Software',
          genre: 'Adventure',
          'SUM(na_sales)': 0.03,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.12,
        },
        {
          publisher: 'Marvelous Interactive',
          genre: 'Sports',
          'SUM(na_sales)': 0.12,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.22,
        },
        {
          publisher: 'Wanadoo',
          genre: 'Action',
          'SUM(na_sales)': 0.27,
          'SUM(eu_sales)': 0.21,
          'SUM(global_sales)': 0.6,
        },
        {
          publisher: 'Virgin Interactive',
          genre: 'Shooter',
          'SUM(na_sales)': 2.45,
          'SUM(eu_sales)': 1.61,
          'SUM(global_sales)': 4.27,
        },
        {
          publisher: 'Titus',
          genre: 'Fighting',
          'SUM(na_sales)': 0.44,
          'SUM(eu_sales)': 0.22,
          'SUM(global_sales)': 0.68,
        },
        {
          publisher: 'Nippon Columbia',
          genre: 'Action',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.53,
        },
        {
          publisher: 'Banpresto',
          genre: 'Simulation',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.7,
        },
        {
          publisher: 'Starfish',
          genre: 'Action',
          'SUM(na_sales)': 0.06,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.06,
        },
        {
          publisher: 'Nordcurrent',
          genre: 'Puzzle',
          'SUM(na_sales)': 0.05,
          'SUM(eu_sales)': 0.13,
          'SUM(global_sales)': 0.2,
        },
        {
          publisher: 'System Soft',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Activision',
          genre: 'Misc',
          'SUM(na_sales)': 48.68,
          'SUM(eu_sales)': 17.63,
          'SUM(global_sales)': 76.5499999999999,
        },
        {
          publisher: 'Mastiff',
          genre: 'Adventure',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: 'Jester Interactive',
          genre: 'Racing',
          'SUM(na_sales)': 0.68,
          'SUM(eu_sales)': 0.28,
          'SUM(global_sales)': 1.11,
        },
        {
          publisher: 'Jack of All Games',
          genre: 'Shooter',
          'SUM(na_sales)': 0.02,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Interplay',
          genre: 'Simulation',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0.04,
          'SUM(global_sales)': 0.1,
        },
        {
          publisher: 'Angel Studios',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.29,
        },
        {
          publisher: 'Kalypso Media',
          genre: 'Misc',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.01,
        },
        {
          publisher: 'ChunSoft',
          genre: 'Action',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.04,
        },
        {
          publisher: 'Ignition Entertainment',
          genre: 'Sports',
          'SUM(na_sales)': 0.16,
          'SUM(eu_sales)': 0.06,
          'SUM(global_sales)': 0.23,
        },
        {
          publisher: 'From Software',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0.11,
          'SUM(eu_sales)': 0.09,
          'SUM(global_sales)': 0.53,
        },
        {
          publisher: 'Acclaim Entertainment',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0.19,
          'SUM(eu_sales)': 0.06,
          'SUM(global_sales)': 0.26,
        },
        {
          publisher: 'Little Orbit',
          genre: 'Simulation',
          'SUM(na_sales)': 0.14,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.15,
        },
        {
          publisher: 'Global Star',
          genre: 'Adventure',
          'SUM(na_sales)': 0.82,
          'SUM(eu_sales)': 0.38,
          'SUM(global_sales)': 1.3,
        },
        {
          publisher: 'Popcorn Arcade',
          genre: 'Platform',
          'SUM(na_sales)': 0.06,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.07,
        },
        {
          publisher: 'Astragon',
          genre: 'Simulation',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Nippon Ichi Software',
          genre: 'Platform',
          'SUM(na_sales)': 0.14,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 0.24,
        },
        {
          publisher: 'Spike',
          genre: 'Sports',
          'SUM(na_sales)': 2.93,
          'SUM(eu_sales)': 0.3,
          'SUM(global_sales)': 3.6,
        },
        {
          publisher: 'Gathering of Developers',
          genre: 'Shooter',
          'SUM(na_sales)': 0.15,
          'SUM(eu_sales)': 0.11,
          'SUM(global_sales)': 0.28,
        },
        {
          publisher: 'Eidos Interactive',
          genre: 'Platform',
          'SUM(na_sales)': 0.81,
          'SUM(eu_sales)': 0.47,
          'SUM(global_sales)': 1.38,
        },
        {
          publisher: 'Koch Media',
          genre: 'Sports',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.11,
          'SUM(global_sales)': 0.13,
        },
        {
          publisher: 'Disney Interactive Studios',
          genre: 'Shooter',
          'SUM(na_sales)': 0.26,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.28,
        },
        {
          publisher: 'Mastertronic',
          genre: 'Sports',
          'SUM(na_sales)': 0.01,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Agetec',
          genre: 'Action',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 0.23,
        },
        {
          publisher: 'Media Works',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: '5pb',
          genre: 'Action',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.13,
        },
        {
          publisher: 'Ocean',
          genre: 'Sports',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.28,
        },
        {
          publisher: 'Virgin Interactive',
          genre: 'Simulation',
          'SUM(na_sales)': 0.15,
          'SUM(eu_sales)': 0.1,
          'SUM(global_sales)': 0.27,
        },
        {
          publisher: 'MC2 Entertainment',
          genre: 'Adventure',
          'SUM(na_sales)': 0.03,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.06,
        },
        {
          publisher: 'Playlogic Game Factory',
          genre: 'Sports',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: 'Virtual Play Games',
          genre: 'Misc',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.04,
        },
        {
          publisher: 'Time Warner Interactive',
          genre: 'Strategy',
          'SUM(na_sales)': 0.05,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 0.09,
        },
        {
          publisher: 'Focus Home Interactive',
          genre: 'Racing',
          'SUM(na_sales)': 0.16,
          'SUM(eu_sales)': 0.17,
          'SUM(global_sales)': 0.37,
        },
        {
          publisher: 'Midway Games',
          genre: 'Racing',
          'SUM(na_sales)': 4.36,
          'SUM(eu_sales)': 1.66,
          'SUM(global_sales)': 6.56,
        },
        {
          publisher: 'Interplay',
          genre: 'Racing',
          'SUM(na_sales)': 0.18,
          'SUM(eu_sales)': 0.13,
          'SUM(global_sales)': 0.37,
        },
        {
          publisher: 'Telstar',
          genre: 'Racing',
          'SUM(na_sales)': 0.05,
          'SUM(eu_sales)': 0.03,
          'SUM(global_sales)': 0.08,
        },
        {
          publisher: 'Spike',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.1,
        },
        {
          publisher: 'Number None',
          genre: 'Platform',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'FuRyu',
          genre: 'Misc',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.24,
        },
        {
          publisher: null,
          genre: 'Misc',
          'SUM(na_sales)': 5.57,
          'SUM(eu_sales)': 2.05,
          'SUM(global_sales)': 7.81,
        },
        {
          publisher: 'Nintendo',
          genre: 'Sports',
          'SUM(na_sales)': 98.77,
          'SUM(eu_sales)': 66.18,
          'SUM(global_sales)': 218.01,
        },
        {
          publisher: 'Rage Software',
          genre: 'Fighting',
          'SUM(na_sales)': 0.6,
          'SUM(eu_sales)': 0.38,
          'SUM(global_sales)': 1.1,
        },
        {
          publisher: 'Tomy Corporation',
          genre: 'Misc',
          'SUM(na_sales)': 0.02,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.03,
        },
        {
          publisher: 'Experience Inc.',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.06,
        },
        {
          publisher: 'Zoo Games',
          genre: 'Action',
          'SUM(na_sales)': 0.26,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.27,
        },
        {
          publisher: 'Midway Games',
          genre: 'Sports',
          'SUM(na_sales)': 12.17,
          'SUM(eu_sales)': 4.55,
          'SUM(global_sales)': 17.94,
        },
        {
          publisher: 'Tomy Corporation',
          genre: 'Racing',
          'SUM(na_sales)': 0.04,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.07,
        },
        {
          publisher: 'ArtDink',
          genre: 'Simulation',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.13,
        },
        {
          publisher: 'Destineer',
          genre: 'Racing',
          'SUM(na_sales)': 0.31,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.33,
        },
        {
          publisher: 'Merscom LLC',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0.17,
          'SUM(global_sales)': 0.2,
        },
        {
          publisher: 'Take-Two Interactive',
          genre: 'Strategy',
          'SUM(na_sales)': 4.07,
          'SUM(eu_sales)': 2.45,
          'SUM(global_sales)': 7.4,
        },
        {
          publisher: 'DTP Entertainment',
          genre: 'Action',
          'SUM(na_sales)': 0.27,
          'SUM(eu_sales)': 0.18,
          'SUM(global_sales)': 0.52,
        },
        {
          publisher: 'Global Star',
          genre: 'Platform',
          'SUM(na_sales)': 0.18,
          'SUM(eu_sales)': 0.08,
          'SUM(global_sales)': 0.29,
        },
        {
          publisher: 'Trion Worlds',
          genre: 'Shooter',
          'SUM(na_sales)': 0.71,
          'SUM(eu_sales)': 0.3,
          'SUM(global_sales)': 1.14,
        },
        {
          publisher: 'Hudson Entertainment',
          genre: 'Misc',
          'SUM(na_sales)': 0.11,
          'SUM(eu_sales)': 0.02,
          'SUM(global_sales)': 0.6,
        },
        {
          publisher: 'GN Software',
          genre: 'Adventure',
          'SUM(na_sales)': 0,
          'SUM(eu_sales)': 0,
          'SUM(global_sales)': 0.05,
        },
        {
          publisher: 'ValuSoft',
          genre: 'Racing',
          'SUM(na_sales)': 0.12,
          'SUM(eu_sales)': 0.09,
          'SUM(global_sales)': 0.24,
        },
        {
          publisher: 'Sega',
          genre: 'Shooter',
          'SUM(na_sales)': 6.15,
          'SUM(eu_sales)': 5.29,
          'SUM(global_sales)': 16.59,
        },
        {
          publisher: 'Coconuts Japan',
          genre: 'Adventure',
          'SUM(na_sales)': 0.01,
          'SUM(eu_sales)': 0.01,
          'SUM(global_sales)': 0.02,
        },
        {
          publisher: 'Ackkstudios',
          genre: 'Role-Playing',
          'SUM(na_sales)': 0.06,
          'SUM(eu_sales)': 0.04,
          'SUM(global_sales)': 0.14,
        },
      ],
    },
  ],
  width: 800,
};
