const queriesDataMetrics2 = {
  cache_key: 'bb08409c3c01818c025db286402da2ae',
  cached_dttm: null,
  cache_timeout: 86400,
  error: null,
  is_cached: true,
  status: 'success',
  stacktrace: null,
  rowcount: 4,
  annotation_data: [],
  data: [
    {
      group_type: 'Direct Due To Group',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
    },
    {
      group_type: 'Due To Group',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
    },
    {
      group_type: 'Summary Group',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 3,
    },
    { group_type: 'Variable', 'COUNT_DISTINCT(period)': 5, 'COUNT_DISTINCT(group_name)': 31 },
  ],
};
const queriesDataMetrics2Breakdowns = {
  cache_key: 'd2cb05cdf3e072a803c4d04040b12fd2',
  cached_dttm: null,
  cache_timeout: 86400,
  error: null,
  is_cached: true,
  status: 'success',
  stacktrace: null,
  rowcount: 8,
  annotation_data: [],
  data: [
    {
      group_type: 'Variable',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 31,
    },
    {
      group_type: 'Variable',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 31,
    },
    {
      group_type: 'Direct Due To Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
    },
    {
      group_type: 'Due To Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
    },
    {
      group_type: 'Summary Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 3,
    },
    {
      group_type: 'Summary Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 3,
    },
    {
      group_type: 'Direct Due To Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 3,
      'COUNT_DISTINCT(group_name)': 6,
    },
    {
      group_type: 'Due To Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 3,
      'COUNT_DISTINCT(group_name)': 6,
    },
  ],
};
const queriesDataForAllCharts = {
  cache_key: '8255e4b82cdfa2332d133f35bae05ca1',
  cached_dttm: null,
  cache_timeout: 86400,
  error: null,
  is_cached: true,
  status: 'success',
  stacktrace: null,
  rowcount: 8,
  annotation_data: [],
  data: [
    {
      group_type: 'Variable',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 31,
      'COUNT_DISTINCT(due_to_group)': 12,
      'COUNT_DISTINCT(efficiency)': 3,
    },
    {
      group_type: 'Variable',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 31,
      'COUNT_DISTINCT(due_to_group)': 12,
      'COUNT_DISTINCT(efficiency)': 3,
    },
    {
      group_type: 'Direct Due To Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
      'COUNT_DISTINCT(due_to_group)': 7,
      'COUNT_DISTINCT(efficiency)': 2,
    },
    {
      group_type: 'Due To Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 7,
      'COUNT_DISTINCT(due_to_group)': 7,
      'COUNT_DISTINCT(efficiency)': 2,
    },
    {
      group_type: 'Summary Group',
      period_type: 'Custom',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 3,
      'COUNT_DISTINCT(due_to_group)': 0,
      'COUNT_DISTINCT(efficiency)': 6,
    },
    {
      group_type: 'Summary Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 5,
      'COUNT_DISTINCT(group_name)': 3,
      'COUNT_DISTINCT(due_to_group)': 0,
      'COUNT_DISTINCT(efficiency)': 6,
    },
    {
      group_type: 'Direct Due To Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 3,
      'COUNT_DISTINCT(group_name)': 6,
      'COUNT_DISTINCT(due_to_group)': 6,
      'COUNT_DISTINCT(efficiency)': 2,
    },
    {
      group_type: 'Due To Group',
      period_type: 'Standard',
      'COUNT_DISTINCT(period)': 3,
      'COUNT_DISTINCT(group_name)': 6,
      'COUNT_DISTINCT(due_to_group)': 6,
      'COUNT_DISTINCT(efficiency)': 2,
    },
  ],
};
const queriesDataTimeSeries = {
  data: [
    { __timestamp: 1508112000000, ds: 1508112000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1506297600000, ds: 1506297600000, 'COUNT(epoch_s)': 5, 'COUNT(epoch_ms)': 5 },
    { __timestamp: 1534723200000, ds: 1534723200000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1505088000000, ds: 1505088000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1509926400000, ds: 1509926400000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1550448000000, ds: 1550448000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1535328000000, ds: 1535328000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1537142400000, ds: 1537142400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1518393600000, ds: 1518393600000, 'COUNT(epoch_s)': 4, 'COUNT(epoch_ms)': 4 },
    { __timestamp: 1540771200000, ds: 1540771200000, 'COUNT(epoch_s)': 4, 'COUNT(epoch_ms)': 4 },
    { __timestamp: 1502064000000, ds: 1502064000000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1549238400000, ds: 1549238400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1535932800000, ds: 1535932800000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1545609600000, ds: 1545609600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1532908800000, ds: 1532908800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1513555200000, ds: 1513555200000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1534118400000, ds: 1534118400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1515369600000, ds: 1515369600000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1502668800000, ds: 1502668800000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1532304000000, ds: 1532304000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1523232000000, ds: 1523232000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1520208000000, ds: 1520208000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1509321600000, ds: 1509321600000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1530489600000, ds: 1530489600000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1504483200000, ds: 1504483200000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1541376000000, ds: 1541376000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1517788800000, ds: 1517788800000, 'COUNT(epoch_s)': 7, 'COUNT(epoch_ms)': 7 },
    { __timestamp: 1538352000000, ds: 1538352000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1522022400000, ds: 1522022400000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1542585600000, ds: 1542585600000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1536537600000, ds: 1536537600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1512345600000, ds: 1512345600000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1551052800000, ds: 1551052800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1508716800000, ds: 1508716800000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1515974400000, ds: 1515974400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1547424000000, ds: 1547424000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1519603200000, ds: 1519603200000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1503273600000, ds: 1503273600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1528070400000, ds: 1528070400000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1531094400000, ds: 1531094400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1524441600000, ds: 1524441600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1522627200000, ds: 1522627200000, 'COUNT(epoch_s)': 5, 'COUNT(epoch_ms)': 5 },
    { __timestamp: 1546214400000, ds: 1546214400000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1538956800000, ds: 1538956800000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1541980800000, ds: 1541980800000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1525046400000, ds: 1525046400000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1527465600000, ds: 1527465600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1545004800000, ds: 1545004800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1514764800000, ds: 1514764800000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1543190400000, ds: 1543190400000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1549843200000, ds: 1549843200000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1551657600000, ds: 1551657600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1523836800000, ds: 1523836800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1518998400000, ds: 1518998400000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1525651200000, ds: 1525651200000, 'COUNT(epoch_s)': 4, 'COUNT(epoch_ms)': 4 },
    { __timestamp: 1526256000000, ds: 1526256000000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1543795200000, ds: 1543795200000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1520812800000, ds: 1520812800000, 'COUNT(epoch_s)': 4, 'COUNT(epoch_ms)': 4 },
    { __timestamp: 1521417600000, ds: 1521417600000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1548633600000, ds: 1548633600000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1506902400000, ds: 1506902400000, 'COUNT(epoch_s)': 3, 'COUNT(epoch_ms)': 3 },
    { __timestamp: 1511740800000, ds: 1511740800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1533513600000, ds: 1533513600000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1505692800000, ds: 1505692800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1514160000000, ds: 1514160000000, 'COUNT(epoch_s)': 4, 'COUNT(epoch_ms)': 4 },
    { __timestamp: 1529280000000, ds: 1529280000000, 'COUNT(epoch_s)': 5, 'COUNT(epoch_ms)': 5 },
    { __timestamp: 1517184000000, ds: 1517184000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1511136000000, ds: 1511136000000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
    { __timestamp: 1529884800000, ds: 1529884800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1526860800000, ds: 1526860800000, 'COUNT(epoch_s)': 2, 'COUNT(epoch_ms)': 2 },
    { __timestamp: 1516579200000, ds: 1516579200000, 'COUNT(epoch_s)': 1, 'COUNT(epoch_ms)': 1 },
  ],
};
const formDataBarsHorizontalLegendTop = {
  queryFields: { groupby: 'groupby', columns: 'groupby' },
  datasource: '13__table',
  vizType: 'composed',
  urlParams: {},
  timeRangeEndpoints: ['inclusive', 'exclusive'],
  timeRange: 'Last week',
  groupby: ['group_type'],
  numbersFormat: 'SMART_NUMBER',
  metrics: [
    {
      expressionType: 'SIMPLE',
      column: {
        id: 442,
        column_name: 'period',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'TEXT',
        python_date_format: null,
        optionName: '_col_period',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(period)',
      optionName: 'metric_zz3gxsxq02_k7xt12w8zsi',
    },
    {
      expressionType: 'SIMPLE',
      column: {
        id: 439,
        column_name: 'group_name',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'TEXT',
        python_date_format: null,
        optionName: '_col_group_name',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(group_name)',
      optionName: 'metric_qmr3yla2hfs_sobd5mwhxh',
    },
  ],
  columns: [],
  adhocFilters: [],
  rowLimit: 100,
  layout: 'horizontal',
  showLegend: true,
  legendPosition: 'top',
  labelsColor: 'white',
  chartType: 'BAR_CHART',
  barChartSubType: 'default',
  lineChartSubType: 'basis',
  areaChartSubType: 'basis',
  scatterChartSubType: 'circle',
  xAxisTickLabelAngle: '45',
  yAxisTickLabelAngle: '0',
  y2AxisTickLabelAngle: '0',
  useCategoryFormattingGroupBy0: true,
  useCategoryFormattingGroupBy1: true,
  useCategoryFormattingGroupBy2: true,
  useCategoryFormattingGroupBy3: true,
  chartTypeMetric0: 'BAR_CHART',
  barChartSubTypeMetric0: 'default',
  lineChartSubTypeMetric0: 'basis',
  areaChartSubTypeMetric0: 'basis',
  scatterChartSubTypeMetric0: 'circle',
  chartTypeMetric1: 'BAR_CHART',
  barChartSubTypeMetric1: 'default',
  lineChartSubTypeMetric1: 'basis',
  areaChartSubTypeMetric1: 'basis',
  scatterChartSubTypeMetric1: 'circle',
  chartTypeMetric2: 'BAR_CHART',
  barChartSubTypeMetric2: 'default',
  lineChartSubTypeMetric2: 'basis',
  areaChartSubTypeMetric2: 'basis',
  scatterChartSubTypeMetric2: 'circle',
  chartTypeMetric3: 'BAR_CHART',
  barChartSubTypeMetric3: 'default',
  lineChartSubTypeMetric3: 'basis',
  areaChartSubTypeMetric3: 'basis',
  scatterChartSubTypeMetric3: 'circle',
  chartTypeMetric4: 'BAR_CHART',
  barChartSubTypeMetric4: 'default',
  lineChartSubTypeMetric4: 'basis',
  areaChartSubTypeMetric4: 'basis',
  scatterChartSubTypeMetric4: 'circle',
  chartTypeMetric5: 'BAR_CHART',
  barChartSubTypeMetric5: 'default',
  lineChartSubTypeMetric5: 'basis',
  areaChartSubTypeMetric5: 'basis',
  scatterChartSubTypeMetric5: 'circle',
  chartTypeMetric6: 'BAR_CHART',
  barChartSubTypeMetric6: 'default',
  lineChartSubTypeMetric6: 'basis',
  areaChartSubTypeMetric6: 'basis',
  scatterChartSubTypeMetric6: 'circle',
  chartTypeMetric7: 'BAR_CHART',
  barChartSubTypeMetric7: 'default',
  lineChartSubTypeMetric7: 'basis',
  areaChartSubTypeMetric7: 'basis',
  scatterChartSubTypeMetric7: 'circle',
  chartTypeMetric8: 'BAR_CHART',
  barChartSubTypeMetric8: 'default',
  lineChartSubTypeMetric8: 'basis',
  areaChartSubTypeMetric8: 'basis',
  scatterChartSubTypeMetric8: 'circle',
  chartTypeMetric9: 'BAR_CHART',
  barChartSubTypeMetric9: 'default',
  lineChartSubTypeMetric9: 'basis',
  areaChartSubTypeMetric9: 'basis',
  scatterChartSubTypeMetric9: 'circle',
  chartTypeMetric10: 'BAR_CHART',
  barChartSubTypeMetric10: 'default',
  lineChartSubTypeMetric10: 'basis',
  areaChartSubTypeMetric10: 'basis',
  scatterChartSubTypeMetric10: 'circle',
  chartTypeMetric11: 'BAR_CHART',
  barChartSubTypeMetric11: 'default',
  lineChartSubTypeMetric11: 'basis',
  areaChartSubTypeMetric11: 'basis',
  scatterChartSubTypeMetric11: 'circle',
  chartTypeMetric12: 'BAR_CHART',
  barChartSubTypeMetric12: 'default',
  lineChartSubTypeMetric12: 'basis',
  areaChartSubTypeMetric12: 'basis',
  scatterChartSubTypeMetric12: 'circle',
  chartTypeMetric13: 'BAR_CHART',
  barChartSubTypeMetric13: 'default',
  lineChartSubTypeMetric13: 'basis',
  areaChartSubTypeMetric13: 'basis',
  scatterChartSubTypeMetric13: 'circle',
  chartTypeMetric14: 'BAR_CHART',
  barChartSubTypeMetric14: 'default',
  lineChartSubTypeMetric14: 'basis',
  areaChartSubTypeMetric14: 'basis',
  scatterChartSubTypeMetric14: 'circle',
  chartTypeMetric15: 'BAR_CHART',
  barChartSubTypeMetric15: 'default',
  lineChartSubTypeMetric15: 'basis',
  areaChartSubTypeMetric15: 'basis',
  scatterChartSubTypeMetric15: 'circle',
  chartTypeMetric16: 'BAR_CHART',
  barChartSubTypeMetric16: 'default',
  lineChartSubTypeMetric16: 'basis',
  areaChartSubTypeMetric16: 'basis',
  scatterChartSubTypeMetric16: 'circle',
  chartTypeMetric17: 'BAR_CHART',
  barChartSubTypeMetric17: 'default',
  lineChartSubTypeMetric17: 'basis',
  areaChartSubTypeMetric17: 'basis',
  scatterChartSubTypeMetric17: 'circle',
  chartTypeMetric18: 'BAR_CHART',
  barChartSubTypeMetric18: 'default',
  lineChartSubTypeMetric18: 'basis',
  areaChartSubTypeMetric18: 'basis',
  scatterChartSubTypeMetric18: 'circle',
  chartTypeMetric19: 'BAR_CHART',
  barChartSubTypeMetric19: 'default',
  lineChartSubTypeMetric19: 'basis',
  areaChartSubTypeMetric19: 'basis',
  scatterChartSubTypeMetric19: 'circle',
  chartTypeMetric20: 'BAR_CHART',
  barChartSubTypeMetric20: 'default',
  lineChartSubTypeMetric20: 'basis',
  areaChartSubTypeMetric20: 'basis',
  scatterChartSubTypeMetric20: 'circle',
  chartTypeMetric21: 'BAR_CHART',
  barChartSubTypeMetric21: 'default',
  lineChartSubTypeMetric21: 'basis',
  areaChartSubTypeMetric21: 'basis',
  scatterChartSubTypeMetric21: 'circle',
  chartTypeMetric22: 'BAR_CHART',
  barChartSubTypeMetric22: 'default',
  lineChartSubTypeMetric22: 'basis',
  areaChartSubTypeMetric22: 'basis',
  scatterChartSubTypeMetric22: 'circle',
  chartTypeMetric23: 'BAR_CHART',
  barChartSubTypeMetric23: 'default',
  lineChartSubTypeMetric23: 'basis',
  areaChartSubTypeMetric23: 'basis',
  scatterChartSubTypeMetric23: 'circle',
  chartTypeMetric24: 'BAR_CHART',
  barChartSubTypeMetric24: 'default',
  lineChartSubTypeMetric24: 'basis',
  areaChartSubTypeMetric24: 'basis',
  scatterChartSubTypeMetric24: 'circle',
  chartTypeMetric25: 'BAR_CHART',
  barChartSubTypeMetric25: 'default',
  lineChartSubTypeMetric25: 'basis',
  areaChartSubTypeMetric25: 'basis',
  scatterChartSubTypeMetric25: 'circle',
  chartTypeMetric26: 'BAR_CHART',
  barChartSubTypeMetric26: 'default',
  lineChartSubTypeMetric26: 'basis',
  areaChartSubTypeMetric26: 'basis',
  scatterChartSubTypeMetric26: 'circle',
  chartTypeMetric27: 'BAR_CHART',
  barChartSubTypeMetric27: 'default',
  lineChartSubTypeMetric27: 'basis',
  areaChartSubTypeMetric27: 'basis',
  scatterChartSubTypeMetric27: 'circle',
  chartTypeMetric28: 'BAR_CHART',
  barChartSubTypeMetric28: 'default',
  lineChartSubTypeMetric28: 'basis',
  areaChartSubTypeMetric28: 'basis',
  scatterChartSubTypeMetric28: 'circle',
  chartTypeMetric29: 'BAR_CHART',
  barChartSubTypeMetric29: 'default',
  lineChartSubTypeMetric29: 'basis',
  areaChartSubTypeMetric29: 'basis',
  scatterChartSubTypeMetric29: 'circle',
  chartTypeMetric30: 'BAR_CHART',
  barChartSubTypeMetric30: 'default',
  lineChartSubTypeMetric30: 'basis',
  areaChartSubTypeMetric30: 'basis',
  scatterChartSubTypeMetric30: 'circle',
  chartTypeMetric31: 'BAR_CHART',
  barChartSubTypeMetric31: 'default',
  lineChartSubTypeMetric31: 'basis',
  areaChartSubTypeMetric31: 'basis',
  scatterChartSubTypeMetric31: 'circle',
  chartTypeMetric32: 'BAR_CHART',
  barChartSubTypeMetric32: 'default',
  lineChartSubTypeMetric32: 'basis',
  areaChartSubTypeMetric32: 'basis',
  scatterChartSubTypeMetric32: 'circle',
  chartTypeMetric33: 'BAR_CHART',
  barChartSubTypeMetric33: 'default',
  lineChartSubTypeMetric33: 'basis',
  areaChartSubTypeMetric33: 'basis',
  scatterChartSubTypeMetric33: 'circle',
  chartTypeMetric34: 'BAR_CHART',
  barChartSubTypeMetric34: 'default',
  lineChartSubTypeMetric34: 'basis',
  areaChartSubTypeMetric34: 'basis',
  scatterChartSubTypeMetric34: 'circle',
  chartTypeMetric35: 'BAR_CHART',
  barChartSubTypeMetric35: 'default',
  lineChartSubTypeMetric35: 'basis',
  areaChartSubTypeMetric35: 'basis',
  scatterChartSubTypeMetric35: 'circle',
  chartTypeMetric36: 'BAR_CHART',
  barChartSubTypeMetric36: 'default',
  lineChartSubTypeMetric36: 'basis',
  areaChartSubTypeMetric36: 'basis',
  scatterChartSubTypeMetric36: 'circle',
  chartTypeMetric37: 'BAR_CHART',
  barChartSubTypeMetric37: 'default',
  lineChartSubTypeMetric37: 'basis',
  areaChartSubTypeMetric37: 'basis',
  scatterChartSubTypeMetric37: 'circle',
  chartTypeMetric38: 'BAR_CHART',
  barChartSubTypeMetric38: 'default',
  lineChartSubTypeMetric38: 'basis',
  areaChartSubTypeMetric38: 'basis',
  scatterChartSubTypeMetric38: 'circle',
  chartTypeMetric39: 'BAR_CHART',
  barChartSubTypeMetric39: 'default',
  lineChartSubTypeMetric39: 'basis',
  areaChartSubTypeMetric39: 'basis',
  scatterChartSubTypeMetric39: 'circle',
  chartTypeMetric40: 'BAR_CHART',
  barChartSubTypeMetric40: 'default',
  lineChartSubTypeMetric40: 'basis',
  areaChartSubTypeMetric40: 'basis',
  scatterChartSubTypeMetric40: 'circle',
  chartTypeMetric41: 'BAR_CHART',
  barChartSubTypeMetric41: 'default',
  lineChartSubTypeMetric41: 'basis',
  areaChartSubTypeMetric41: 'basis',
  scatterChartSubTypeMetric41: 'circle',
  chartTypeMetric42: 'BAR_CHART',
  barChartSubTypeMetric42: 'default',
  lineChartSubTypeMetric42: 'basis',
  areaChartSubTypeMetric42: 'basis',
  scatterChartSubTypeMetric42: 'circle',
  chartTypeMetric43: 'BAR_CHART',
  barChartSubTypeMetric43: 'default',
  lineChartSubTypeMetric43: 'basis',
  areaChartSubTypeMetric43: 'basis',
  scatterChartSubTypeMetric43: 'circle',
  chartTypeMetric44: 'BAR_CHART',
  barChartSubTypeMetric44: 'default',
  lineChartSubTypeMetric44: 'basis',
  areaChartSubTypeMetric44: 'basis',
  scatterChartSubTypeMetric44: 'circle',
  chartTypeMetric45: 'BAR_CHART',
  barChartSubTypeMetric45: 'default',
  lineChartSubTypeMetric45: 'basis',
  areaChartSubTypeMetric45: 'basis',
  scatterChartSubTypeMetric45: 'circle',
  chartTypeMetric46: 'BAR_CHART',
  barChartSubTypeMetric46: 'default',
  lineChartSubTypeMetric46: 'basis',
  areaChartSubTypeMetric46: 'basis',
  scatterChartSubTypeMetric46: 'circle',
  chartTypeMetric47: 'BAR_CHART',
  barChartSubTypeMetric47: 'default',
  lineChartSubTypeMetric47: 'basis',
  areaChartSubTypeMetric47: 'basis',
  scatterChartSubTypeMetric47: 'circle',
  chartTypeMetric48: 'BAR_CHART',
  barChartSubTypeMetric48: 'default',
  lineChartSubTypeMetric48: 'basis',
  areaChartSubTypeMetric48: 'basis',
  scatterChartSubTypeMetric48: 'circle',
  chartTypeMetric49: 'BAR_CHART',
  barChartSubTypeMetric49: 'default',
  lineChartSubTypeMetric49: 'basis',
  areaChartSubTypeMetric49: 'basis',
  scatterChartSubTypeMetric49: 'circle',
};
const formDataBarsHorizontalLegendLeftY2Axis = {
  ...formDataBarsHorizontalLegendTop,
  legendPosition: 'left',
  useY2Axis: true,
  y2AxisLabel: 'Label 2',
  tickLabelAngle2: '90',
};
const formDataBarsVerticalLegendRightNumFormatAllLabels = {
  ...formDataBarsHorizontalLegendTop,
  layout: 'vertical',
  showLegend: true,
  legendPosition: 'right',
  numbersFormat: 'SMART_NUMBER',
  labelsColor: 'black',
  chartType: 'BAR_CHART',
  barChartSubType: 'stacked',
  lineChartSubType: 'basis',
  areaChartSubType: 'basis',
  scatterChartSubType: 'circle',
  xAxisLabel: 'XLabel',
  xAxisTickLabelAngle: '0',
  yAxisLabel: 'YLabel',
  yAxisTickLabelAngle: '45',
  useY2Axis: true,
  y2AxisTickLabelAngle: '0',
};
const formDataWithAllChartTypes = {
  numbersFormat: 'SMART_NUMBER',
  queryFields: { groupby: 'groupby', columns: 'groupby' },
  datasource: '13__table',
  vizType: 'composed',
  urlParams: { URL_IS_TOO_LONG_TO_SHARE: '' },
  timeRangeEndpoints: ['inclusive', 'exclusive'],
  timeRange: 'Last week',
  groupby: ['group_type'],
  metrics: [
    {
      expressionType: 'SIMPLE',
      column: {
        id: 442,
        column_name: 'period',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'TEXT',
        python_date_format: null,
        optionName: '_col_period',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(period)',
      optionName: 'metric_pgoatq2ztj_89vhh4gcums',
    },
    {
      expressionType: 'SIMPLE',
      column: {
        id: 439,
        column_name: 'group_name',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'TEXT',
        python_date_format: null,
        optionName: '_col_group_name',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(group_name)',
      optionName: 'metric_lmdhe0lkblg_elv2tmnvmq9',
    },
    {
      expressionType: 'SIMPLE',
      column: {
        id: 446,
        column_name: 'due_to_group',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'TEXT',
        python_date_format: null,
        optionName: '_col_due_to_group',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(due_to_group)',
      optionName: 'metric_c98ay692tm5_sta4btkbwrs',
    },
    {
      expressionType: 'SIMPLE',
      column: {
        id: 461,
        column_name: 'efficiency',
        verbose_name: null,
        description: null,
        expression: null,
        filterable: true,
        groupby: true,
        is_dttm: false,
        type: 'DOUBLE PRECISION',
        python_date_format: null,
        optionName: '_col_efficiency',
      },
      aggregate: 'COUNT_DISTINCT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT_DISTINCT(efficiency)',
      optionName: 'metric_audvel3jew_xu9l29kfkuj',
    },
  ],
  columns: ['period_type'],
  adhocFilters: [],
  rowLimit: 100,
  layout: 'horizontal',
  showLegend: true,
  legendPosition: 'bottom',
  labelsColor: 'black',
  chartType: 'BAR_CHART',
  barChartSubType: 'stacked',
  lineChartSubType: 'basis',
  areaChartSubType: 'basis',
  scatterChartSubType: 'circle',
  xAxisLabel: '',
  xAxisTickLabelAngle: '0',
  yAxisLabel: 'QWEr',
  yAxisTickLabelAngle: '45',
  useY2Axis: true,
  y2AxisTickLabelAngle: '0',
  useCustomTypeMetric0: true,
  useCategoryFormattingGroupBy0: true,
  useCategoryFormattingGroupBy1: true,
  useCategoryFormattingGroupBy2: true,
  useCategoryFormattingGroupBy3: true,
  chartTypeMetric0: 'AREA_CHART',
  barChartSubTypeMetric0: 'default',
  lineChartSubTypeMetric0: 'linear',
  areaChartSubTypeMetric0: 'basis',
  scatterChartSubTypeMetric0: 'circle',
  useCustomTypeMetric1: true,
  chartTypeMetric1: 'LINE_CHART',
  barChartSubTypeMetric1: 'default',
  lineChartSubTypeMetric1: 'linear',
  areaChartSubTypeMetric1: 'basis',
  scatterChartSubTypeMetric1: 'circle',
  useCustomTypeMetric2: true,
  chartTypeMetric2: 'SCATTER_CHART',
  barChartSubTypeMetric2: 'default',
  lineChartSubTypeMetric2: 'basis',
  areaChartSubTypeMetric2: 'basis',
  scatterChartSubTypeMetric2: 'circle',
  useCustomTypeMetric3: true,
  chartTypeMetric3: 'BAR_CHART',
  barChartSubTypeMetric3: 'default',
  lineChartSubTypeMetric3: 'basis',
  areaChartSubTypeMetric3: 'basis',
  scatterChartSubTypeMetric3: 'circle',
  chartTypeMetric4: 'BAR_CHART',
  barChartSubTypeMetric4: 'stacked',
  lineChartSubTypeMetric4: 'basis',
  areaChartSubTypeMetric4: 'basis',
  scatterChartSubTypeMetric4: 'circle',
  chartTypeMetric5: 'BAR_CHART',
  barChartSubTypeMetric5: 'default',
  lineChartSubTypeMetric5: 'basis',
  areaChartSubTypeMetric5: 'basis',
  scatterChartSubTypeMetric5: 'circle',
};
const formDataTimeSeries = {
  ...formDataBarsHorizontalLegendTop,
  vizType: 'composed',
  datasource: '7__table',
  sliceId: 945,
  urlParams: { URL_IS_TOO_LONG_TO_SHARE: '' },
  timeRangeEndpoints: ['inclusive', 'exclusive'],
  granularitySqla: 'ds',
  timeGrainSqla: 'P1W',
  timeRange: "DATEADD(DATETIME('2021-05-09T00:00:00'), -15, quarter) : 2021-05-09T00:00:00",
  groupby: ['ds'],
  metrics: [
    {
      expressionType: 'SIMPLE',
      column: {
        column_name: 'epoch_s',
        description: null,
        expression: '',
        filterable: true,
        groupby: true,
        id: 373,
        is_dttm: true,
        python_date_format: 'epoch_s',
        type: 'BIGINT',
        verbose_name: null,
      },
      aggregate: 'COUNT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT(epoch_s)',
      optionName: 'metric_58ye4y88shq_o4x9bysahlq',
    },
    {
      expressionType: 'SIMPLE',
      column: {
        id: 372,
        column_name: 'epoch_ms',
        verbose_name: null,
        description: null,
        expression: '',
        filterable: true,
        groupby: true,
        is_dttm: true,
        type: 'BIGINT',
        python_date_format: 'epoch_ms',
      },
      aggregate: 'COUNT',
      sqlExpression: null,
      isNew: false,
      hasCustomLabel: false,
      label: 'COUNT(epoch_ms)',
      optionName: 'metric_slranrxrccp_nkm00ls6xf',
    },
  ],
  columns: [],
  adhocFilters: [],
  rowLimit: 100,
  layout: 'horizontal',
  showLegend: true,
  legendPosition: 'top',
  numbersFormat: 'SMART_NUMBER',
  chartType: 'BAR_CHART',
  barChartSubType: 'stacked',
  lineChartSubType: 'basis',
  areaChartSubType: 'basis',
  scatterChartSubType: 'circle',
  labelsColor: 'white',
  minBarWidth: '60',
  showTotals: true,
  xAxisTickLabelAngle: '0',
  yAxisLabelAngle: '0',
  yAxisTickLabelAngle: '0',
  y2AxisLabelAngle: '0',
  y2AxisTickLabelAngle: '0',
  useCategoryFormattingGroupBy0: true,
  extraFormData: {},
};

export const barsHorizontalLegendTop = {
  formData: formDataBarsHorizontalLegendTop,
  height: 400,
  queriesData: [queriesDataMetrics2],
  width: 800,
};

export const barsHorizontalLegendLeftY2AxisBreakdowns = {
  formData: formDataBarsHorizontalLegendLeftY2Axis,
  height: 400,
  queriesData: [queriesDataMetrics2Breakdowns],
  width: 800,
};

export const barsVerticalLegendRightNumFormatAllLabelsBreakdowns = {
  formData: formDataBarsVerticalLegendRightNumFormatAllLabels,
  height: 400,
  queriesData: [queriesDataMetrics2Breakdowns],
  width: 800,
};

export const allChatsLegendBottomBreakdowns = {
  formData: formDataWithAllChartTypes,
  height: 400,
  queriesData: [queriesDataForAllCharts],
  width: 800,
};

export const timeSeries = {
  formData: formDataTimeSeries,
  height: 400,
  queriesData: [queriesDataTimeSeries],
  width: 800,
};
