name: build-and-test-workflow

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build packages
      run: yarn build
    - name: Run ESLint
      run: yarn lint --quiet
    - name: Run unit tests
      run: yarn test
