export const extractArgs = <A extends object>(args: A, baseProps: A): A =>
  Object.entries(args).reduce(
    // We need to clean args that comes from storybook table as `undefiled` values that were automatically generated by TS props
    (acc, [argKey, argVal]) => {
      if (Array.isArray(argVal) && argVal.every(v => v === undefined)) {
        return acc;
      }
      if (argVal === undefined) {
        return acc;
      }
      return { ...acc, [argKey]: argVal };
    },
    { ...baseProps },
  );

export const extractTransformProps = ({ args, props, transformProps, formData = {} }) => ({
  ...transformProps({
    ...extractArgs<typeof args>(args, props),
    formData: {
      ...extractArgs<typeof args>(args, props.formData),
      ...formData,
    },
  }),
});
